# Generated by Django 3.2 on 2021-08-31 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.IntegerField()),
                ('date_to_launch', models.IntegerField()),
                ('description', models.TextField(max_length=60)),
                ('link_to_join', models.CharField(max_length=30)),
                ('solicitudes_to_join', models.IntegerField()),
                ('privacy', models.CharField(blank=None, choices=[('private', 'Private'), ('public', 'Public')], default='unknown', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.IntegerField()),
                ('date_to_launch', models.IntegerField()),
                ('description', models.TextField(max_length=60)),
                ('likes', models.IntegerField()),
                ('time_shared', models.IntegerField()),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.IntegerField()),
                ('date_to_launch', models.IntegerField()),
                ('description', models.TextField(max_length=60)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.post')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
