# Generated by Django 3.2 on 2021-09-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=30)),
                ('creation_date', models.CharField(max_length=30)),
                ('chatroom', models.CharField(max_length=30)),
            ],
        ),
    ]
