# Generated by Django 3.2 on 2021-09-22 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_name', models.CharField(max_length=30)),
                ('creation_date', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('link_to_join', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='chatroom_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.chatroom'),
        ),
    ]
