# Generated by Django 3.2 on 2022-02-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210922_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='asunto',
            field=models.CharField(default='conversation', max_length=30),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(default='a normal conversation', max_length=60),
        ),
    ]
